class InvitationType:
    DEVICE: InvitationType
    USER: InvitationType
    def __init__(self, value: str) -> None: ...
    def value(self) -> str: ...

class UserProfile:
    ADMIN: UserProfile
    STANDARD: UserProfile
    OUTSIDER: UserProfile
    def __init__(self, value: str) -> None: ...
    @classmethod
    def iter(cls) -> list[UserProfile]: ...
    def value(self) -> str: ...
